/**
 * Online/Offline synchronization contract — shared between client and server.
 *
 * Three endpoints, no more (`SYNC_STRATEGY.md` §2):
 *  - `GET  /api/sync/snapshot` — full snapshot used to bootstrap the local cache;
 *  - `GET  /api/sync/pull?since=` — delta since a cursor (changes from other devices);
 *  - `POST /api/sync/push` — **idempotent** ingestion of the outbox, in causal order.
 *
 * Principles applied here:
 *  - the client emits **intents** identified by `clientUuid`; the server is the
 *    authority on legal numbers, consolidated stock and accounting entries ([BR-8]);
 *  - a replayed operation returns `duplicate` + the already-created id, **without writing**;
 *  - a dependency not yet resolved returns `deferred`: the client replays on the next
 *    cycle instead of failing permanently (`SYNC_STRATEGY.md` §4).
 */

import { z } from "zod";

/** Entities accepted for offline writes, prefixed by domain. */
export const SYNC_ENTITIES = [
  "core.party",
  "catalog.product",
  "sales.quote",
  "invoicing.sales_invoice",
  "payments.payment",
  "pos.session_open",
  "pos.session_close",
  "inventory.stock_movement",
  "catalog.category",
  "services.service",
] as const;
export type SyncEntity = (typeof SYNC_ENTITIES)[number];

export const syncEntitySchema = z.enum(SYNC_ENTITIES);

/**
 * `conflict` (offline-first workstations only): an update found a sensitive field
 * changed on the server since the version it started from. Nothing was written.
 */
export const SYNC_OPERATION_STATUSES = [
  "created",
  "duplicate",
  "error",
  "deferred",
  "conflict",
] as const;
export type SyncOperationStatus = (typeof SYNC_OPERATION_STATUSES)[number];

/** Document line carried by an offline operation. */
export const syncDocumentLineSchema = z.object({
  productId: z.string().uuid().nullish(),
  /** Product itself created offline: resolved via the batch's `catalog.product` operation. */
  productClientUuid: z.string().uuid().nullish(),
  variantId: z.string().uuid().nullish(),
  serviceId: z.string().uuid().nullish(),
  description: z.string().min(1),
  productSku: z.string().default(""),
  quantity: z.union([z.number().positive(), z.string().regex(/^\s*\d+(\.\d{1,3})?\s*$/)]),
  unit: z.string().default("unité"),
  unitPriceCents: z.number().int().min(0),
  discountBp: z.number().int().min(0).max(10_000).default(0),
});
export type SyncDocumentLine = z.infer<typeof syncDocumentLineSchema>;

export const syncPartyPayloadSchema = z.object({
  name: z.string().min(1),
  partyType: z.enum(["CUSTOMER", "SUPPLIER", "BOTH", "PROSPECT"]).default("CUSTOMER"),
  email: z.string().default(""),
  phone: z.string().default(""),
  taxId: z.string().default(""),
  creditLimitCents: z.number().int().min(0).default(0),
  paymentTermsDays: z.number().int().min(0).default(0),
  notes: z.string().default(""),
});

export const syncProductPayloadSchema = z.object({
  /** Empty: the code is generated by the server. */
  sku: z.string().default(""),
  name: z.string().min(1),
  description: z.string().default(""),
  unit: z.string().default("unité"),
  barcode: z.string().default(""),
  salePriceCents: z.number().int().default(0),
  purchasePriceCents: z.number().int().default(0),
  isService: z.boolean().default(false),
  categoryId: z.string().uuid().nullish(),
  minStock: z.union([z.number(), z.string()]).default("0"),
  initialStock: z
    .object({
      warehouseId: z.string().uuid(),
      quantity: z.union([z.number().min(0), z.string().regex(/^\s*\d+(\.\d{1,3})?\s*$/)]),
      unitCostCents: z.number().int().min(0).default(0),
    })
    .nullish(),
});

export const syncInvoicePayloadSchema = z.object({
  partyId: z.string().uuid().nullish(),
  /** Customer created in the same offline batch. */
  partyClientUuid: z.string().uuid().nullish(),
  warehouseId: z.string().uuid().nullish(),
  posSessionId: z.string().uuid().nullish(),
  posSessionClientUuid: z.string().uuid().nullish(),
  source: z.enum(["MANUAL", "ORDER", "POS"]).default("POS"),
  date: z.string(),
  dueDate: z.string().nullish(),
  globalDiscountBp: z.number().int().min(0).max(10_000).default(0),
  notes: z.string().default(""),
  /** Provisional number shown offline; replaced by the final number on ACK. */
  provisionalNumber: z.string().default(""),
  lines: z.array(syncDocumentLineSchema).min(1),
});

export const syncQuotePayloadSchema = z.object({
  partyId: z.string().uuid().nullish(),
  partyClientUuid: z.string().uuid().nullish(),
  date: z.string(),
  expiryDate: z.string().nullish(),
  globalDiscountBp: z.number().int().min(0).max(10_000).default(0),
  notes: z.string().default(""),
  provisionalNumber: z.string().default(""),
  lines: z.array(syncDocumentLineSchema).min(1),
});

export const syncPaymentPayloadSchema = z.object({
  partyId: z.string().uuid().nullish(),
  partyClientUuid: z.string().uuid().nullish(),
  invoiceId: z.string().uuid().nullish(),
  invoiceClientUuid: z.string().uuid().nullish(),
  bankAccountId: z.string().uuid().nullish(),
  posSessionId: z.string().uuid().nullish(),
  posSessionClientUuid: z.string().uuid().nullish(),
  amountCents: z.number().int().positive(),
  paymentDate: z.string(),
  paymentMethod: z.enum(["CASH", "BANK_TRANSFER", "CHECK", "CARD", "MOBILE_MONEY"]).default("CASH"),
  reference: z.string().default(""),
  notes: z.string().default(""),
});

export const syncSessionOpenPayloadSchema = z.object({
  registerId: z.string().uuid(),
  openingBalanceCents: z.number().int().default(0),
  openedAt: z.string(),
  notes: z.string().default(""),
});

export const syncSessionClosePayloadSchema = z.object({
  sessionId: z.string().uuid().nullish(),
  sessionClientUuid: z.string().uuid().nullish(),
  closingBalanceCents: z.number().int().default(0),
  closedAt: z.string(),
  notes: z.string().default(""),
});

export const syncStockMovementPayloadSchema = z.object({
  productId: z.string().uuid(),
  warehouseId: z.string().uuid(),
  movementType: z.enum(["IN", "OUT", "ADJUSTMENT", "RETURN"]),
  /** Explicit direction of an adjustment; otherwise inferred from the movement type. */
  direction: z.enum(["IN", "OUT"]).nullish(),
  quantity: z.union([z.number().positive(), z.string().regex(/^\s*\d+(\.\d{1,3})?\s*$/)]),
  unitCostCents: z.number().int().min(0).nullish(),
  reason: z.string().default(""),
  lotNumber: z.string().default(""),
});

export const syncCategoryPayloadSchema = z.object({
  name: z.string().min(1),
  parentId: z.string().uuid().nullish(),
  description: z.string().default(""),
});

export const syncServicePayloadSchema = z.object({
  code: z.string().min(1),
  name: z.string().min(1),
  description: z.string().default(""),
  billingType: z.enum(["HOURLY", "DAILY", "FLAT"]).default("HOURLY"),
  priceCents: z.number().int().min(0).default(0),
});

/**
 * Payload of an `update` or `delete` of reference data (offline-first workstations).
 * `changes`: the fields entered, validated like the online `PATCH`. `base`: the value
 * each of those fields had when the change started — the server compares it with its
 * own to tell a concurrent change from an unchanged field.
 */
export const syncChangePayloadSchema = z.object({
  changes: z.record(z.unknown()).default({}),
  base: z.record(z.unknown()).default({}),
});
export type SyncChangePayload = z.infer<typeof syncChangePayloadSchema>;

/** Single outbox operation. */
export const syncOperationSchema = z.object({
  /** Idempotency key generated on the device (UUIDv4). */
  clientUuid: z.string().uuid(),
  /** Monotonic local counter: guarantees the causal replay order (`SYNC_STRATEGY.md` §4). */
  localSeq: z.number().int().nonnegative(),
  entity: syncEntitySchema,
  action: z.enum(["create", "update", "delete"]).default("create"),
  /** Row changed by an `update` or `delete`. */
  entityId: z.string().uuid().optional(),
  /** Server version the change started from; absent: no conflict check. */
  baseVersion: z.number().int().nonnegative().nullish(),
  /** `clientUuid`s of the operations this one depends on; otherwise `deferred`. */
  dependsOn: z.array(z.string().uuid()).default([]),
  createdAt: z.string(),
  payload: z.record(z.unknown()),
});
export type SyncOperationInput = z.infer<typeof syncOperationSchema>;

export const syncPushRequestSchema = z.object({
  deviceId: z.string().min(1).max(128),
  /** Beyond this, the client splits: a batch must stay processable in a single HTTP request. */
  operations: z.array(syncOperationSchema).max(200),
});
export type SyncPushRequest = z.infer<typeof syncPushRequestSchema>;

export interface SyncOperationResult {
  clientUuid: string;
  entity: SyncEntity;
  status: SyncOperationStatus;
  /** Server id created (or existing, for a `duplicate`). */
  serverId?: string;
  /** Final legal number assigned — replaces the provisional number on the client. */
  assignedNumber?: string;
  /** Human-readable error message (in the request language), present when `status` is `error` or `deferred`. */
  detail?: string;
  /**
   * Outcome in the terms of offline-first workstations: `created` and `duplicate` are
   * both a `success` (the server holds the data), `error` is `failed`.
   */
  outcome: SyncOutcome;
  /** Fields changed on both sides (`conflict`). */
  conflictFields?: string[];
  /** Current server row of the entity, when it has one: stored as is by the workstation. */
  record?: { entity: SyncTable } & SyncRecord;
}

export type SyncOutcome = "success" | "conflict" | "failed" | "deferred";

export function outcomeOf(status: SyncOperationStatus): SyncOutcome {
  if (status === "created" || status === "duplicate") return "success";
  if (status === "error") return "failed";
  return status;
}

export interface SyncPushResponse {
  results: SyncOperationResult[];
  /** Cursor to pass to the next `pull`. */
  cursor: string;
  serverTime: string;
}

/** Maps each entity to its payload schema. */
export const SYNC_PAYLOAD_SCHEMAS = {
  "core.party": syncPartyPayloadSchema,
  "catalog.product": syncProductPayloadSchema,
  "sales.quote": syncQuotePayloadSchema,
  "invoicing.sales_invoice": syncInvoicePayloadSchema,
  "payments.payment": syncPaymentPayloadSchema,
  "pos.session_open": syncSessionOpenPayloadSchema,
  "pos.session_close": syncSessionClosePayloadSchema,
  "inventory.stock_movement": syncStockMovementPayloadSchema,
  "catalog.category": syncCategoryPayloadSchema,
  "services.service": syncServicePayloadSchema,
} as const satisfies Record<SyncEntity, z.ZodTypeAny>;

/** Local table holding the rows of each entity (none for stock movements). */
export const SYNC_ENTITY_TABLES: Record<SyncEntity, SyncTable | null> = {
  "core.party": "parties",
  "catalog.product": "products",
  "sales.quote": "quotes",
  "invoicing.sales_invoice": "sales_invoices",
  "payments.payment": "payments",
  "pos.session_open": "pos_sessions",
  "pos.session_close": "pos_sessions",
  "inventory.stock_movement": null,
  "catalog.category": "categories",
  "services.service": "services",
};

/** Recommended replay order when two operations share the same `localSeq`. */
export const SYNC_ENTITY_PRIORITY: Record<SyncEntity, number> = {
  "catalog.category": 5,
  "core.party": 10,
  "catalog.product": 10,
  "services.service": 10,
  "pos.session_open": 20,
  "sales.quote": 30,
  "invoicing.sales_invoice": 40,
  "payments.payment": 50,
  "inventory.stock_movement": 60,
  "pos.session_close": 90,
};

/** Canonical batch ordering: `localSeq` first, entity priority as tie-breaker. */
export function sortOperations<T extends { localSeq: number; entity: SyncEntity }>(
  operations: T[]
): T[] {
  return [...operations].sort(
    (a, b) =>
      a.localSeq - b.localSeq || SYNC_ENTITY_PRIORITY[a.entity] - SYNC_ENTITY_PRIORITY[b.entity]
  );
}

// ---------------------------------------------------------------------------------------
// Offline-first workstation (`docs/OFFLINE_SYNC.md`)
//
//  - `POST /api/sync/bootstrap`             → starting cursor and what to download;
//  - `GET  /api/sync/bootstrap/:entity`     → one page of an entity, by increasing id;
//  - `GET  /api/sync/pull?cursor=&limit=`   → changes after the cursor, from the change log.
// ---------------------------------------------------------------------------------------

/**
 * Tables mirrored on the workstation, **in dependency order**: the bootstrap downloads
 * them in this order and a workstation applies them in it. Same names as the server
 * tables and the local SQLite tables (`src-tauri/src/local_db/migrations.rs`).
 */
export const SYNC_TABLES = [
  "companies",
  "company_settings",
  "company_plugins",
  "categories",
  "warehouses",
  "bank_accounts",
  "pos_registers",
  "parties",
  "products",
  "services",
  "stock_items",
  "pos_sessions",
  "quotes",
  "sales_orders",
  "sales_invoices",
  "credit_notes",
  "purchase_orders",
  "goods_receipts",
  "supplier_invoices",
  "payments",
] as const;
export type SyncTable = (typeof SYNC_TABLES)[number];

export function isSyncTable(value: string): value is SyncTable {
  return (SYNC_TABLES as readonly string[]).includes(value);
}

/** Months of document history downloaded at the first synchronization. */
export const BOOTSTRAP_HISTORY_MONTHS = 12;
/** Rows per bootstrap page. */
export const BOOTSTRAP_PAGE_SIZE = 500;
/** Changes per pull page (a single larger transaction is served whole). */
export const PULL_PAGE_SIZE = 500;

/** A server row as stored on the workstation: the table row plus its child rows. */
export interface SyncRecord {
  id: string;
  version: number;
  data: Record<string, unknown>;
}

export interface BootstrapStartResponse {
  /**
   * Pull cursor to use once every page is stored. Taken **before** the first page is
   * read: whatever changes while the pages download is served again by the pull.
   */
  cursor: number;
  /** Start of the document history window (`YYYY-MM-DD`), to pass to every page. */
  since: string;
  /** Entities this person may receive, in dependency order, with their row counts. */
  entities: { entity: SyncTable; total: number }[];
}

export interface BootstrapPageResponse {
  entity: SyncTable;
  rows: SyncRecord[];
  /** Id to pass as `after` for the next page; `null` when done. */
  nextAfter: string | null;
  done: boolean;
}

export interface PullChange {
  entity: SyncTable;
  entityId: string;
  /** `UPSERT`: `data` is the current row. `DELETE`: the row no longer exists. */
  operation: "UPSERT" | "DELETE";
  version?: number;
  data?: Record<string, unknown>;
}

export interface PullResponse {
  cursor: number;
  hasMore: boolean;
  /** The server log no longer covers the cursor: bootstrap again. */
  resync: boolean;
  /**
   * Entities this person may receive. Changes of the others are **not** in `changes`:
   * a workstation holding one of them must consider it stale and download it again
   * when someone allowed to see it synchronizes.
   */
  scope: SyncTable[];
  changes: PullChange[];
}

export const bootstrapPageQuerySchema = z.object({
  after: z.string().uuid().optional(),
  limit: z.coerce.number().int().min(1).max(2000).default(BOOTSTRAP_PAGE_SIZE),
  since: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/)
    .optional(),
});

export const pullQuerySchema = z.object({
  cursor: z.coerce.number().int().min(0),
  limit: z.coerce.number().int().min(1).max(5000).default(PULL_PAGE_SIZE),
});
