/**
 * Applies the SQL migrations generated by `drizzle-kit generate`.
 *
 * Preferred over `drizzle-kit push` in production: `push` diffs the schema and applies
 * differences computed on the fly, which can destroy a renamed column. Versioned
 * migrations, on the other hand, are reviewed before being run.
 */

import "dotenv/config";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { migrate } from "drizzle-orm/node-postgres/migrator";

import { closeDatabase, db } from "../server/db";

const migrationsFolder = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "migrations"
);

async function main(): Promise<void> {
  console.log(`→ Applying migrations from ${migrationsFolder}…`);
  await migrate(db, { migrationsFolder });
  console.log("✔ Migrations applied.");
}

main()
  .then(async () => {
    await closeDatabase();
    process.exit(0);
  })
  .catch(async (error) => {
    console.error("Migrations failed:", error);
    await closeDatabase();
    process.exit(1);
  });
